/**
 * JARVIS PDF Export
 * Browser-based PDF generation via print-to-PDF
 * Creates a styled HTML document in a new window and triggers print
 */

import type { ChatMessage } from "@/lib/types";

interface PDFExportOptions {
  title: string;
  subtitle?: string;
  content: string;
  includeHeader?: boolean;
  includeFooter?: boolean;
  date?: string;
}

/**
 * Generate a styled HTML page for PDF export
 */
export function generatePDFHTML(options: PDFExportOptions): string {
  const { title, subtitle, content, includeHeader = true, includeFooter = true, date } = options;
  const now = date || new Date().toLocaleString("ru-RU", {
    year: "numeric", month: "long", day: "numeric", hour: "2-digit", minute: "2-digit"
  });

  return `<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>${escapeHtml(title)}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@300;400;500;600&family=Inter:wght@300;400;500;600&display=swap');

    * { margin: 0; padding: 0; box-sizing: border-box; }

    @page {
      size: A4;
      margin: 2cm;
    }

    body {
      font-family: 'Inter', -apple-system, sans-serif;
      font-size: 11pt;
      line-height: 1.6;
      color: #1a1a2e;
      background: #fff;
      padding: 2cm;
    }

    .header {
      border-bottom: 2px solid #00d4ff;
      padding-bottom: 16px;
      margin-bottom: 24px;
    }

    .header h1 {
      font-family: 'JetBrains Mono', monospace;
      font-size: 18pt;
      font-weight: 600;
      color: #0a0a1a;
      letter-spacing: 2px;
      text-transform: uppercase;
    }

    .header .subtitle {
      font-family: 'JetBrains Mono', monospace;
      font-size: 9pt;
      color: #666;
      margin-top: 4px;
      letter-spacing: 1px;
    }

    .header .meta {
      display: flex;
      justify-content: space-between;
      margin-top: 8px;
      font-size: 8pt;
      color: #999;
      font-family: 'JetBrains Mono', monospace;
    }

    .content {
      margin-top: 16px;
    }

    .content pre {
      background: #f5f5f5;
      border: 1px solid #e0e0e0;
      border-radius: 4px;
      padding: 12px;
      font-family: 'JetBrains Mono', monospace;
      font-size: 9pt;
      overflow-x: auto;
      white-space: pre-wrap;
      word-break: break-word;
    }

    .content code {
      font-family: 'JetBrains Mono', monospace;
      background: #f0f0f0;
      padding: 1px 4px;
      border-radius: 2px;
      font-size: 9pt;
    }

    .content p { margin-bottom: 12px; }
    .content ul, .content ol { margin-left: 20px; margin-bottom: 12px; }
    .content li { margin-bottom: 4px; }
    .content h2 { font-size: 14pt; margin: 20px 0 8px; color: #0a0a1a; }
    .content h3 { font-size: 12pt; margin: 16px 0 6px; color: #333; }
    .content blockquote {
      border-left: 3px solid #00d4ff;
      padding-left: 12px;
      margin: 12px 0;
      color: #555;
      font-style: italic;
    }

    .message {
      margin-bottom: 16px;
      padding: 12px;
      border-radius: 6px;
      page-break-inside: avoid;
    }

    .message.user {
      background: #f0f7ff;
      border-left: 3px solid #00d4ff;
    }

    .message.assistant {
      background: #f9f9f9;
      border-left: 3px solid #666;
    }

    .message-role {
      font-family: 'JetBrains Mono', monospace;
      font-size: 8pt;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 1px;
      margin-bottom: 4px;
    }

    .message.user .message-role { color: #0088cc; }
    .message.assistant .message-role { color: #444; }

    .message-content {
      font-size: 10pt;
      line-height: 1.5;
    }

    .footer {
      border-top: 1px solid #e0e0e0;
      padding-top: 12px;
      margin-top: 32px;
      display: flex;
      justify-content: space-between;
      font-size: 8pt;
      color: #999;
      font-family: 'JetBrains Mono', monospace;
    }
  </style>
</head>
<body>
  ${includeHeader ? `
  <div class="header">
    <h1>${escapeHtml(title)}</h1>
    ${subtitle ? `<div class="subtitle">${escapeHtml(subtitle)}</div>` : ""}
    <div class="meta">
      <span>J.A.R.V.I.S. AI Assistant</span>
      <span>${now}</span>
    </div>
  </div>
  ` : ""}
  <div class="content">
    ${content}
  </div>
  ${includeFooter ? `
  <div class="footer">
    <span>Generated by J.A.R.V.I.S. v20.0</span>
    <span>${now}</span>
  </div>
  ` : ""}
</body>
</html>`;
}

/**
 * Export chat messages as PDF
 */
export function generateChatPDF(messages: ChatMessage[], title?: string): string {
  const content = messages
    .filter(m => m.role !== "system")
    .map(m => {
      const role = m.role === "user" ? "User" : "J.A.R.V.I.S.";
      const escapedContent = m.content
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/\n/g, "<br>");

      return `<div class="message ${m.role}">
        <div class="message-role">${role}</div>
        <div class="message-content">${escapedContent}</div>
      </div>`;
    })
    .join("\n");

  return generatePDFHTML({
    title: title || "JARVIS Chat Export",
    subtitle: `${messages.filter(m => m.role !== "system").length} сообщений`,
    content,
  });
}

/**
 * Generate briefing PDF content
 */
export function generateBriefingPDF(briefing: { title: string; sections: Array<{ heading: string; content: string }> }): string {
  const content = briefing.sections
    .map(s => `<h2>${escapeHtml(s.heading)}</h2><p>${escapeHtml(s.content).replace(/\n/g, "</p><p>")}</p>`)
    .join("\n");

  return generatePDFHTML({
    title: briefing.title,
    subtitle: "Daily Intelligence Briefing",
    content,
  });
}

/**
 * Open PDF in print dialog
 */
export function printPDF(html: string) {
  const win = window.open("", "_blank");
  if (!win) {
    // Fallback: create downloadable HTML
    downloadPDFFallback(html);
    return;
  }
  win.document.write(html);
  win.document.close();
  // Wait for styles to load, then print
  win.onload = () => {
    setTimeout(() => win.print(), 500);
  };
}

/**
 * Download as HTML file (fallback when popup blocked)
 */
function downloadPDFFallback(html: string) {
  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `jarvis-export-${Date.now()}.html`;
  a.click();
  URL.revokeObjectURL(url);
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}